name: CI

on: [push, pull_request]

jobs:
  basic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        path: ./src/github.com/neilpa/yajsv
    - name: Build
      run: make ci
    - name: List Files
      shell: bash
      run: ls -altr
